"""Convert dataset.pkl into a set of human-readable CSV files.

The pickle is a nested dict with three logically distinct sub-tables:

  dataset.pkl
  ├── 'analysis'   nested dict[system][DP_N] -> dict of curves/samples
  │                  rdf_amorphous, rdf_crystal:  tuple (r-array, g(r)-array), len 64
  │                  msid_data:                   tuple (n-array, msid-array), len 11
  │                  ree_data, rg_data:           ndarray of per-chain samples, len 210
  │                  dp:                          int (redundant with DP_N key)
  ├── 'tg'         nested dict[system][DP_N] -> dict of equal-length arrays
  │                  Temp, MSD_1ps ... MSD_10ps, each len 42
  └── 'mechanics'  pandas DataFrame, shape (327, 38), indexed by folder_name

Because the sub-tables have incompatible row shapes, a single flat CSV would
not be readable. Instead we emit one CSV per natural table into ./csv/, plus a
README. Curve-shaped data is written in long ("tidy") format. The tg/MSD table
is wide since each temperature row has all 10 time-window MSDs.

Run:   python convert_pkl_to_csv.py
"""
from __future__ import annotations

import pickle
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent  # .../demos/npjcompmat/data/
PKL = HERE / "dataset.pkl"
OUT = HERE / "csv"


def _dp_int(dp_key: str) -> int:
    """'DP_10' -> 10"""
    return int(dp_key.split("_")[1])


# ---- per-table converters -------------------------------------------------


def convert_mechanics(mech: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    df = mech.reset_index()  # surface folder_name as a regular column

    # Rewrite legacy absolute-ish graph_file paths like
    #   '10_0_26_75_43_53_9\\output\\network_N6x6x6_trial6.gpickle'
    # into live relative paths from the demo root:
    #   'data/mechanics/10_0_26_75_43_53_9/network_N6x6x6_trial6.gpickle'
    def _rewrite(gf: str) -> str:
        parts = str(gf).replace("\\", "/").split("/")
        folder, basename = parts[0], parts[-1]
        return f"data/mechanics/{folder}/{basename}"

    df["graph_file"] = df["graph_file"].map(_rewrite)
    df.to_csv(out_dir / "mechanics.csv", index=False)
    return df


def _rdf_long(analysis: dict, key: str) -> pd.DataFrame:
    rows = []
    for system, dps in analysis.items():
        for dp_key, leaf in dps.items():
            dp = leaf.get("dp", _dp_int(dp_key))
            r_arr, g_arr = leaf[key]
            for r, g in zip(r_arr, g_arr):
                rows.append({"system": system, "dp": dp, "r": float(r), "g_r": float(g)})
    return pd.DataFrame(rows)


def convert_rdf(analysis: dict, key: str, out_name: str, out_dir: Path) -> pd.DataFrame:
    df = _rdf_long(analysis, key)
    df.to_csv(out_dir / out_name, index=False)
    return df


def convert_msid(analysis: dict, out_dir: Path) -> pd.DataFrame:
    rows = []
    for system, dps in analysis.items():
        for dp_key, leaf in dps.items():
            dp = leaf.get("dp", _dp_int(dp_key))
            n_arr, msid_arr = leaf["msid_data"]
            for n, m in zip(n_arr, msid_arr):
                rows.append({"system": system, "dp": dp, "n": int(n), "msid": float(m)})
    df = pd.DataFrame(rows)
    df.to_csv(out_dir / "analysis_msid.csv", index=False)
    return df


def convert_samples(
    analysis: dict, key: str, value_col: str, out_name: str, out_dir: Path
) -> pd.DataFrame:
    rows = []
    for system, dps in analysis.items():
        for dp_key, leaf in dps.items():
            dp = leaf.get("dp", _dp_int(dp_key))
            arr = leaf[key]
            for i, v in enumerate(arr):
                rows.append(
                    {"system": system, "dp": dp, "sample_idx": i, value_col: float(v)}
                )
    df = pd.DataFrame(rows)
    df.to_csv(out_dir / out_name, index=False)
    return df


def convert_tg(tg: dict, out_dir: Path) -> pd.DataFrame:
    rows = []
    for system, dps in tg.items():
        for dp_key, leaf in dps.items():
            dp = _dp_int(dp_key)
            temps = leaf["Temp"]
            msd_cols = [k for k in leaf if k.startswith("MSD_")]
            for i, T in enumerate(temps):
                row = {"system": system, "dp": dp, "Temp": int(T)}
                for col in msd_cols:
                    row[col] = float(leaf[col][i])
                rows.append(row)
    df = pd.DataFrame(rows)
    df.to_csv(out_dir / "tg_msd.csv", index=False)
    return df


# ---- README ---------------------------------------------------------------

README_TEMPLATE = """# CSV exports of `dataset.pkl`

Generated by `convert_pkl_to_csv.py`. Each file is one natural sub-table of the
original pickle. Re-run the script to regenerate after the pickle changes.

Systems: **PDMS**, **PMTFPS**. DP values: **10**, **30**, **100**.

| File | Shape | Format | Description |
|---|---|---|---|
| `mechanics.csv` | {mech_shape} | wide | Per-simulation metrics (mechanical + topological). `folder_name` is the case ID. |
| `analysis_rdf_amorphous.csv` | {rdf_a_shape} | long | Radial distribution function g(r) in the amorphous state. Columns: system, dp, r, g_r. |
| `analysis_rdf_crystal.csv` | {rdf_c_shape} | long | Same as above, crystalline state. |
| `analysis_msid.csv` | {msid_shape} | long | Mean squared internal distance vs. intra-chain separation. Columns: system, dp, n, msid. |
| `analysis_ree_samples.csv` | {ree_shape} | long | Per-chain end-to-end distance samples. Columns: system, dp, sample_idx, ree. |
| `analysis_rg_samples.csv` | {rg_shape} | long | Per-chain radius of gyration samples. Columns: system, dp, sample_idx, rg. |
| `tg_msd.csv` | {tg_shape} | wide | Temperature-resolved MSD used for Tg extraction. Columns: system, dp, Temp, MSD_1ps ... MSD_10ps. |

The original `dataset.pkl` remains the authoritative source; these CSVs are for
human inspection and loading from non-Python tools.
"""


def _shape(df: pd.DataFrame) -> str:
    return f"{df.shape[0]} x {df.shape[1]}"


def main() -> None:
    with open(PKL, "rb") as f:
        data = pickle.load(f)

    OUT.mkdir(exist_ok=True)
    print(f"Writing CSVs to {OUT.relative_to(HERE.parent)}/")

    mech_df = convert_mechanics(data["mechanics"], OUT)
    rdf_a_df = convert_rdf(data["analysis"], "rdf_amorphous", "analysis_rdf_amorphous.csv", OUT)
    rdf_c_df = convert_rdf(data["analysis"], "rdf_crystal", "analysis_rdf_crystal.csv", OUT)
    msid_df = convert_msid(data["analysis"], OUT)
    ree_df = convert_samples(data["analysis"], "ree_data", "ree", "analysis_ree_samples.csv", OUT)
    rg_df = convert_samples(data["analysis"], "rg_data", "rg", "analysis_rg_samples.csv", OUT)
    tg_df = convert_tg(data["tg"], OUT)

    readme = README_TEMPLATE.format(
        mech_shape=_shape(mech_df),
        rdf_a_shape=_shape(rdf_a_df),
        rdf_c_shape=_shape(rdf_c_df),
        msid_shape=_shape(msid_df),
        ree_shape=_shape(ree_df),
        rg_shape=_shape(rg_df),
        tg_shape=_shape(tg_df),
    )
    (OUT / "README.md").write_text(readme, encoding="utf-8")

    for name, df in [
        ("mechanics.csv", mech_df),
        ("analysis_rdf_amorphous.csv", rdf_a_df),
        ("analysis_rdf_crystal.csv", rdf_c_df),
        ("analysis_msid.csv", msid_df),
        ("analysis_ree_samples.csv", ree_df),
        ("analysis_rg_samples.csv", rg_df),
        ("tg_msd.csv", tg_df),
    ]:
        print(f"  {name:35s} {_shape(df)}")
    print("  README.md")


if __name__ == "__main__":
    main()
