"""LAMMPS data + settings + input-script writer for a MARTINI protein system.

Emits six files (the first three sibling to ``output_dir``, the three relaxation
stage scripts under ``output_dir/relaxation/``):

* ``<base>.data``                       LAMMPS data file (atom_style full):
                                         Atoms, Bonds, Angles, Dihedrals,
                                         Impropers + their type counts.
* ``<base>.in.settings``                pair_coeff / bond_coeff / angle_coeff /
                                         etc. lines covering every type id used
                                         in the data file.
* ``<base>.in.groups``                  group definitions for protein vs. water.
* ``relaxation/<base>_stage1.in``       soft-push overlap removal.
* ``relaxation/<base>_stage2.in``       LJ-epsilon ramp 0.001 -> 1.0 via
                                         nve/limit dynamics.
* ``relaxation/<base>_stage3.in``       tight CG min + brief NVT/NPT @ 310 K
                                         (uses ``units real``,
                                         ``lj/cut/coul/cut``, ``dielectric=15``,
                                         no PPPM).

LAMMPS units: ``real`` (Angstrom, kcal/mol). MARTINI bonded-term conversions
live in `martini_ff` and are exercised here.

GROMACS function-type mapping:

* bond funct 1 (harmonic)        ->  bond_style harmonic
* angle funct 2 (cosine sq.)     ->  angle_style cosine/squared
* angle funct 10 (restricted)    ->  angle_style cosine/squared (omits 1/sin^2 t,
                                                                 first-cut surrogate)
* dihedral funct 9 (proper, multi-term)  ->  dihedral_style charmm
                                              (one type per term; multiple
                                               types per quadruplet allowed)
* dihedral funct 2 (improper, harmonic)  ->  improper_style harmonic
                                              (placed in the Impropers section)
* `[ constraints ]`              ->  emitted as ULTRA-stiff harmonic bonds
                                     (K = 1e6 kJ/mol/nm^2, matching the
                                      reference's `#ifdef FLEXIBLE` block).
                                     A `fix shake` block is offered as an
                                     opt-in alternative in the input script
                                     comments.

Reaction-field electrostatics are approximated with `dielectric 15.0` plus
`pair_style lj/cut/coul/cut`, mirroring the reference's `coulombtype = reaction-field
epsilon_r = 15`. The RF correction term is omitted (documented in the .in
header).
"""
from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path

from .martini_ff import (
    KJ_TO_KCAL,
    MartiniLibrary,
    gmx_angle_k_kjmol_to_lammps,
    gmx_bond_k_to_lammps,
    gmx_dihedral_k_to_lammps,
    gmx_lj_to_lammps,
)
from .system import System

CONSTRAINT_K_GMX: float = 10_000.0  # kJ/(mol*nm^2). Soft enough that mis-placed
# sidechain beads don't explode during NVT; users wanting true rigidity should
# add `fix shake` referencing the constraint bond_type ids in the input script.
HEADER_BANNER: str = (
    "# LAMMPS data file generated by topon.protein_network\n"
    "# MARTINI 3 protein network. Sequence- and BFM-driven.\n"
    "# Reaction-field electrostatics approximated as dielectric=15.0.\n"
)


def _bond_type_key(bond) -> tuple:
    if bond.is_crosslink:
        return ("crosslink", round(bond.length_nm, 4), round(bond.k_kj, 1))
    return (bond.funct, round(bond.length_nm, 4), round(bond.k_kj, 1))


def _constraint_type_key(c) -> tuple:
    return ("constraint", round(c.length_nm, 4))


def _angle_type_key(a) -> tuple:
    return (a.funct, round(a.angle_deg, 3), round(a.k_kj, 3))


def _dihedral_type_key(d) -> tuple:
    return (d.funct, round(d.angle_deg, 3), round(d.k_kj, 3), d.mult, d.is_improper)


def _assign_ids(records: list, key_fn) -> tuple[dict, list[int]]:
    """Return (key->type_id, per-record-type-id-list)."""
    type_ids: dict = OrderedDict()
    per_record: list[int] = []
    for r in records:
        k = key_fn(r)
        if k not in type_ids:
            type_ids[k] = len(type_ids) + 1
        per_record.append(type_ids[k])
    return type_ids, per_record


_BB_BEAD_TYPES: set[str] = {"Q5", "SP1", "P2", "SP2", "SP2a"}
_WATER_BEAD_TYPES: set[str] = {"W", "WF", "SW", "TW"}
_CROSSLINK_BEAD_TYPES: set[str] = {"TN6"}  # TYR SC4 = dityrosine site


def write_lammps(
    sys_: System,
    library: MartiniLibrary,
    output_dir: str | Path,
    *,
    base_name: str = "protein_network",
    include_input_script: bool = True,
    hierarchical_stage1: bool = False,
    coord_perturbation_ang: float = 0.05,
    coord_perturbation_seed: int = 7,
) -> dict[str, Path]:
    """Write the LAMMPS files for `sys_`. Returns paths keyed by artifact name
    (``data``, ``settings``, ``groups``, ``stage1``, ``stage2``, ``stage3``).

    If `hierarchical_stage1=True`, emits the core-topon-style progressive
    freeze/unfreeze stage 1 (mirrors `topon/writers/lammps_inputs.py:33` for
    CG networks), and adds per-class group definitions (bb/sc/crosslink/water)
    to the .in.groups file. Otherwise emits the flat topro-style stage 1.

    `coord_perturbation_ang`: per-axis Gaussian xyz jitter applied at write
    time (default 0.05 A). Mirrors core topon's pattern of breaking
    zero-distance degeneracies (e.g. dityrosine BB-BB pairs that BFM merges
    onto one lattice node) before LAMMPS sees them. Set to 0 to disable.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Type assignment ----------------------------------------------------------
    bead_types = sys_.bead_types_in_use()
    bead_type_id = {bt: i + 1 for i, bt in enumerate(bead_types)}

    # Treat constraints as additional bonds with ULTRA-stiff K
    constraint_bonds = [
        (c.a, c.b, "constraint", c.length_nm, CONSTRAINT_K_GMX, False)
        for c in sys_.constraints
    ]
    real_bonds = [
        (b.a, b.b, b.funct, b.length_nm, b.k_kj, b.is_crosslink)
        for b in sys_.bonds
    ]
    all_bonds = real_bonds + constraint_bonds

    bond_type_keys: OrderedDict = OrderedDict()
    bond_per_record: list[int] = []
    for (_a, _b, funct, length, k, is_crosslink) in all_bonds:
        if funct == "constraint":
            key = ("constraint", round(length, 4))
        elif is_crosslink:
            key = ("crosslink", round(length, 4), round(k, 1))
        else:
            key = (funct, round(length, 4), round(k, 1))
        if key not in bond_type_keys:
            bond_type_keys[key] = len(bond_type_keys) + 1
        bond_per_record.append(bond_type_keys[key])

    angle_type_keys, angle_per_record = _assign_ids(sys_.angles, _angle_type_key)

    propers = [d for d in sys_.dihedrals if not d.is_improper]
    impropers = [d for d in sys_.dihedrals if d.is_improper]
    dihedral_type_keys, dihedral_per_record = _assign_ids(propers, _dihedral_type_key)
    improper_type_keys, improper_per_record = _assign_ids(impropers, _dihedral_type_key)

    # Data file ----------------------------------------------------------------
    data_path = out / f"{base_name}.data"
    with data_path.open("w", encoding="utf-8") as f:
        f.write(HEADER_BANNER)
        f.write("\n")
        f.write(f"{sys_.n_atoms()} atoms\n")
        f.write(f"{len(all_bonds)} bonds\n")
        f.write(f"{len(sys_.angles)} angles\n")
        f.write(f"{len(propers)} dihedrals\n")
        f.write(f"{len(impropers)} impropers\n\n")
        f.write(f"{len(bead_types)} atom types\n")
        f.write(f"{len(bond_type_keys)} bond types\n")
        f.write(f"{max(1, len(angle_type_keys))} angle types\n")
        f.write(f"{max(1, len(dihedral_type_keys))} dihedral types\n")
        f.write(f"{max(1, len(improper_type_keys))} improper types\n\n")
        bx, by, bz = sys_.box_dims_ang
        f.write(f"0.0 {bx:.6f} xlo xhi\n")
        f.write(f"0.0 {by:.6f} ylo yhi\n")
        f.write(f"0.0 {bz:.6f} zlo zhi\n\n")

        f.write("Masses\n\n")
        for bt, tid in bead_type_id.items():
            mass = library.atomtypes[bt].mass if bt in library.atomtypes else 72.0
            f.write(f"{tid} {mass:.4f}  # {bt}\n")
        f.write("\n")

        f.write("Atoms  # full\n\n")
        bx, by, bz = sys_.box_dims_ang
        # Tiny xyz perturbation to break zero-distance degeneracies (BFM
        # merges two crosslink endpoints onto one lattice node, so their BBs
        # are coincident in the wrapped frame; without a jitter the bond/
        # angle gradient computation hits division-by-zero in stage 1).
        # Mirrors core topon's hierarchical-relaxation precondition.
        import numpy as _np
        _pert_rng = _np.random.default_rng(coord_perturbation_seed)
        for b in sys_.beads:
            tid = bead_type_id[b.bead_type]
            # Wrap-only convention (matches core topon writer). All atoms
            # placed inside [0, box); no image flag column. LAMMPS handles
            # bonds across periodic boundaries via the neighbor/ghost system
            # using min-image distance, which is correct as long as every
            # bond is shorter than box/2 (always the case for MARTINI 3.6 A
            # bonds in a >= 240 A box).
            if coord_perturbation_ang > 0.0:
                jx, jy, jz = _pert_rng.normal(0.0, coord_perturbation_ang, size=3)
            else:
                jx = jy = jz = 0.0
            x = (b.position[0] + jx) % bx
            y = (b.position[1] + jy) % by
            z = (b.position[2] + jz) % bz
            f.write(
                f"{b.atom_id} {b.molecule_id} {tid} {b.charge:.4f} "
                f"{x:.6f} {y:.6f} {z:.6f}  "
                f"# {b.residue_name}/{b.atom_name} {b.bead_type}\n"
            )
        f.write("\n")

        if all_bonds:
            f.write("Bonds\n\n")
            for i, (a, b, funct, length, k, is_xl) in enumerate(all_bonds, start=1):
                tid = bond_per_record[i - 1]
                tag = "crosslink" if is_xl else ("constraint" if funct == "constraint" else "bond")
                f.write(f"{i} {tid} {a} {b}  # {tag}\n")
            f.write("\n")

        if sys_.angles:
            f.write("Angles\n\n")
            for i, ang in enumerate(sys_.angles, start=1):
                tid = angle_per_record[i - 1]
                f.write(f"{i} {tid} {ang.a} {ang.b} {ang.c}\n")
            f.write("\n")

        if propers:
            f.write("Dihedrals\n\n")
            for i, d in enumerate(propers, start=1):
                tid = dihedral_per_record[i - 1]
                f.write(f"{i} {tid} {d.a} {d.b} {d.c} {d.d}\n")
            f.write("\n")

        if impropers:
            f.write("Impropers\n\n")
            for i, d in enumerate(impropers, start=1):
                tid = improper_per_record[i - 1]
                f.write(f"{i} {tid} {d.a} {d.b} {d.c} {d.d}\n")
            f.write("\n")

    # Settings file ------------------------------------------------------------
    settings_path = out / f"{base_name}.in.settings"
    with settings_path.open("w", encoding="utf-8") as f:
        f.write("# pair_coeff: explicit MARTINI 3 nonbond_params (LAMMPS units real).\n")
        for i, bt_i in enumerate(bead_types, start=1):
            for j, bt_j in enumerate(bead_types[i - 1:], start=i):
                sigma_nm, eps_kj = library.get_lj_pair(bt_i, bt_j)
                sigma_a, eps_kcal = gmx_lj_to_lammps(sigma_nm, eps_kj)
                f.write(
                    f"pair_coeff {i} {j} {eps_kcal:.6f} {sigma_a:.6f}  "
                    f"# {bt_i}-{bt_j}\n"
                )
        f.write("\n# bond_coeff: harmonic for real bonds + constraint bonds (ULTRA stiff).\n")
        for key, tid in bond_type_keys.items():
            kind = key[0]
            if kind == "constraint":
                length_nm = key[1]
                k_l = gmx_bond_k_to_lammps(CONSTRAINT_K_GMX)
                f.write(
                    f"bond_coeff {tid} {k_l:.6f} {length_nm * 10:.6f}  "
                    f"# constraint (rigid-stiff)\n"
                )
            elif kind == "crosslink":
                length_nm, k_kj = key[1], key[2]
                k_l = gmx_bond_k_to_lammps(k_kj)
                f.write(
                    f"bond_coeff {tid} {k_l:.6f} {length_nm * 10:.6f}  "
                    f"# dityrosine crosslink\n"
                )
            else:
                funct, length_nm, k_kj = key
                k_l = gmx_bond_k_to_lammps(k_kj)
                f.write(
                    f"bond_coeff {tid} {k_l:.6f} {length_nm * 10:.6f}  "
                    f"# funct {funct} K={k_kj} kJ/mol/nm^2 r0={length_nm} nm\n"
                )

        if angle_type_keys:
            f.write("\n# angle_coeff: cosine/squared (covers funct 2 and approximates funct 10).\n")
            for key, tid in angle_type_keys.items():
                funct, angle_deg, k_kj = key
                k_l = gmx_angle_k_kjmol_to_lammps(k_kj)
                f.write(
                    f"angle_coeff {tid} {k_l:.6f} {angle_deg:.4f}  "
                    f"# funct {funct}\n"
                )

        if dihedral_type_keys:
            f.write("\n# dihedral_coeff: charmm style for funct 9 (proper, multi-term).\n")
            for key, tid in dihedral_type_keys.items():
                funct, angle_deg, k_kj, mult, _is_imp = key
                k_l = gmx_dihedral_k_to_lammps(k_kj)
                # CHARMM style: K (kcal/mol), n (mult), d (degrees), w=0 (no 1-4 weight override)
                f.write(
                    f"dihedral_coeff {tid} {k_l:.6f} {mult} {int(round(angle_deg))} 0.0  "
                    f"# funct {funct}\n"
                )

        if improper_type_keys:
            f.write("\n# improper_coeff: harmonic (funct 2 -- TYR ring planarity, etc.).\n")
            for key, tid in improper_type_keys.items():
                funct, angle_deg, k_kj, _mult, _is_imp = key
                k_l = gmx_angle_k_kjmol_to_lammps(k_kj)
                f.write(
                    f"improper_coeff {tid} {k_l:.6f} {angle_deg:.4f}  "
                    f"# funct {funct}\n"
                )

    # Groups file --------------------------------------------------------------
    groups_path = out / f"{base_name}.in.groups"
    with groups_path.open("w", encoding="utf-8") as f:
        protein_mols = sorted({b.molecule_id for b in sys_.beads if b.bead_type != "W"})
        water_mols = sorted({b.molecule_id for b in sys_.beads if b.bead_type == "W"})
        if protein_mols:
            lo, hi = protein_mols[0], protein_mols[-1]
            f.write(f"group protein molecule {lo}:{hi}\n")
        if water_mols:
            lo, hi = water_mols[0], water_mols[-1]
            f.write(f"group water molecule {lo}:{hi}\n")
        f.write(f"# {len(protein_mols)} protein chains, {len(water_mols)} W water beads\n")
        if hierarchical_stage1:
            # Per-class type groups for the hierarchical freeze/unfreeze protocol.
            # MARTINI 3 protein bead types fall into 4 classes:
            #   bb        = backbone (BB beads of all residues; types depend on residue)
            #   sc        = sidechains (excluding the TYR SC4 dityrosine site)
            #   crosslink = TN6 (TYR SC4) -- the merged BFM lattice site bead
            #   water     = W
            f.write("\n# Hierarchical-relaxation per-class groups (used by stage 1)\n")
            bb_ids = sorted(tid for bt, tid in bead_type_id.items() if bt in _BB_BEAD_TYPES)
            sc_ids = sorted(tid for bt, tid in bead_type_id.items()
                             if bt not in (_BB_BEAD_TYPES | _WATER_BEAD_TYPES | _CROSSLINK_BEAD_TYPES))
            xl_ids = sorted(tid for bt, tid in bead_type_id.items() if bt in _CROSSLINK_BEAD_TYPES)
            w_ids = sorted(tid for bt, tid in bead_type_id.items() if bt in _WATER_BEAD_TYPES)
            if bb_ids: f.write(f"group bb type {' '.join(map(str, bb_ids))}\n")
            if sc_ids: f.write(f"group sc type {' '.join(map(str, sc_ids))}\n")
            if xl_ids: f.write(f"group crosslink type {' '.join(map(str, xl_ids))}\n")
            if w_ids: f.write(f"group wbeads type {' '.join(map(str, w_ids))}\n")

    paths: dict[str, Path] = {
        "data": data_path,
        "settings": settings_path,
        "groups": groups_path,
    }

    if include_input_script:
        relax_dir = out / "relaxation"
        relax_dir.mkdir(parents=True, exist_ok=True)
        stage1_path = relax_dir / f"{base_name}_stage1.in"
        stage2_path = relax_dir / f"{base_name}_stage2.in"
        stage3_path = relax_dir / f"{base_name}_stage3.in"
        if hierarchical_stage1:
            stage1_path.write_text(_stage1_hierarchical(base_name, bool(w_ids if hierarchical_stage1 else False)), encoding="utf-8")
        else:
            stage1_path.write_text(_stage1_soft(base_name), encoding="utf-8")
        stage2_path.write_text(_stage2_ljramp(base_name), encoding="utf-8")
        stage3_path.write_text(_stage3_min_nvt_npt(base_name), encoding="utf-8")
        paths["stage1"] = stage1_path
        paths["stage2"] = stage2_path
        paths["stage3"] = stage3_path

    return paths


def _stage1_hierarchical(base_name: str, has_water: bool) -> str:
    """Hierarchical freeze/unfreeze soft-push, mirroring core topon
    `lammps_inputs.py:write_serial_soft_minimization` for CG networks.

    Adapted for MARTINI -- the key wrinkle is that BFM-derived dityrosine
    crosslinks place two SC4 atoms at exactly r=0 (same merged lattice node),
    so they MUST be free to separate during the first soft-push minimization
    or the LJ in stage 2 blows up. Therefore we only freeze the backbone in
    Stage A, then unfreeze for Stage B.

    Stages:
      A: freeze bb -> sc + crosslink + water relax (crosslinks separate to ~2.7A)
      B: unfreeze bb -> full soft minimisation
    """
    return f"""# Stage 1 -- Hierarchical soft-push (topon.protein_network, MARTINI 3).
# Mirrors core topon's progressive freeze/unfreeze pattern from
# topon/writers/lammps_inputs.py:write_serial_soft_minimization, adapted so
# the dityrosine crosslink atoms (TN6, initially at r=0 with their partner)
# can separate before LJ engagement in stage 2.
# Run from this relaxation/ directory.

{_COMMON_HEADER}
pair_style      lj/cut/coul/cut 12.0
pair_modify     shift yes
special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0
dielectric      15.0

read_data       ../{base_name}.data
include         ../{base_name}.in.settings
include         ../{base_name}.in.groups

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes one 10000
comm_modify     mode single cutoff 60.0

# Switch to soft potential
pair_style      soft 1.0
pair_coeff      * * 0.0
variable        prefactor equal ramp(0,60)

thermo          100
thermo_style    custom step pe ke etotal evdwl epair ebond eangle press vol

# === Stage A: freeze backbone; sc + crosslink (+ water if present) relax ===
# Backbone frozen so the BFM-derived chain skeleton is preserved while
# sidechains and dityrosine crosslink atoms (initially overlapping) find space.
fix             freeze_bb bb setforce 0 0 0
fix             soft_push all adapt 1 pair soft a * * v_prefactor
min_style       cg
minimize        1.0e-4 1.0e-6 5000 50000
unfix           soft_push
unfix           freeze_bb
write_data      min_stage_A.data

# === Stage B: full soft minimisation (everything free) ===
fix             soft_push all adapt 1 pair soft a * * v_prefactor
minimize        1.0e-4 1.0e-6 5000 50000
unfix           soft_push

# === Stage C: nve/limit dynamics + final min ===
# CG minimize gets stuck at the r=0 saddle of the soft potential (gradient=0
# at the cosine peak); brief NVE/limit dynamics nudges atoms off it. This is
# the same pattern core topon uses for atomistic relaxation
# (lammps_inputs.py:141-145).
reset_timestep  0
timestep        1.0
fix             soft_push all adapt 1 pair soft a * * v_prefactor
fix             nve_limit all nve/limit 0.1
run             1000
unfix           nve_limit
unfix           soft_push
fix             soft_push all adapt 1 pair soft a * * v_prefactor
minimize        1.0e-4 1.0e-6 5000 50000
unfix           soft_push

write_data      system_after_soft.data
write_restart   1.restart
print           "Stage 1 (hierarchical) done -> system_after_soft.data"
"""


_COMMON_HEADER = """units           real
boundary        p p p
atom_style      full
bond_style      harmonic
angle_style     cosine/squared
dihedral_style  charmm
improper_style  harmonic
"""


def _stage1_soft(base_name: str) -> str:
    return f"""# Stage 1 -- Soft-push overlap removal (topon.protein_network, MARTINI 3).
# Resolves overlaps from the BFM lattice -> Cartesian projection and the
# voxel-grid water packer. Adapted from the topro CHARMM stage 1 protocol.
# Run from this relaxation/ directory.

{_COMMON_HEADER}
pair_style      lj/cut/coul/cut 12.0
pair_modify     shift yes
special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0
dielectric      15.0

read_data       ../{base_name}.data
include         ../{base_name}.in.settings
include         ../{base_name}.in.groups

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes one 10000
comm_modify     mode single cutoff 60.0  # MARTINI bonds + sidechains can stretch under soft potential  # tolerate stretched IDP backbone bonds

# Switch to soft potential for overlap removal
pair_style      soft 1.0
pair_coeff      * * 0.0
variable        prefactor equal ramp(0,60)

thermo          100
thermo_style    custom step pe ke etotal evdwl ecoul epair ebond eangle edihed eimp press vol

# Stage A: ramped soft push under CG minimisation
fix             soft_push all adapt 1 pair soft a * * v_prefactor
min_style       cg
minimize        1.0e-4 1.0e-6 1000 10000
unfix           soft_push
write_data      min_stage_A.data

# Stage B: brief nve/limit dynamics under soft potential
reset_timestep  0
timestep        1.0
fix             soft_push all adapt 1 pair soft a * * v_prefactor
fix             nve_limit all nve/limit 0.1
run             1000
unfix           nve_limit
unfix           soft_push

# Stage C: final soft minimisation
fix             soft_push all adapt 1 pair soft a * * v_prefactor
minimize        1.0e-4 1.0e-6 1000 10000
unfix           soft_push

write_data      system_after_soft.data
write_restart   1.restart
print           "Stage 1 done -> system_after_soft.data"
"""


def _stage2_ljramp(base_name: str) -> str:
    return f"""# Stage 2 -- LJ epsilon ramp 0.001 -> 1.0 (topon.protein_network, MARTINI 3).
# Engages MARTINI 3 LJ interactions gradually under nve/limit dynamics.
# Adapted from the topro CHARMM stage 2 protocol; switched from
# lj/charmm/coul/long to MARTINI's lj/cut/coul/cut.
# Run from this relaxation/ directory.

{_COMMON_HEADER}
pair_style      soft 1.0

read_data       system_after_soft.data
include         ../{base_name}.in.groups

neigh_modify    one 10000
comm_modify     mode single cutoff 60.0  # MARTINI bonds + sidechains can stretch under soft potential

# Pre-minimise once more under soft potential
pair_coeff      * * 1.0
min_style       cg
minimize        1.0e-4 1.0e-6 1000 10000

# Switch to MARTINI lj/cut/coul/cut (supports `fix adapt` epsilon scaling)
pair_style      lj/cut/coul/cut 12.0
pair_modify     shift yes
special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0
dielectric      15.0
include         ../{base_name}.in.settings

variable        scale equal ramp(0.001,1.0)
timestep        1.0

thermo          1000
thermo_style    custom step pe ke etotal evdwl ecoul epair ebond eangle edihed eimp press vol temp

fix             1 all adapt 1 pair lj/cut/coul/cut epsilon * * v_scale scale yes
fix             fxnve all nve/limit 0.1
run             20000
unfix           fxnve
unfix           1

write_data      system_ramped.data
write_restart   2.restart
print           "Stage 2 done -> system_ramped.data"
"""


def _stage3_min_nvt_npt(base_name: str) -> str:
    return f"""# Stage 3 -- Tight min + short NVT + (optional) NPT.
# Faithful MARTINI 3 port of topro's CHARMM stage 3 (same structure, same
# 1 fs timestep, same 100.0 Tdamp). MARTINI-specific changes are noted inline:
#   * pair_style lj/cut/coul/cut    (vs lj/charmm/coul/long + kspace pppm)
#   * dielectric 15.0               (RF approximation; MARTINI default)
#   * special_bonds lj/coul 0 0 0   (vs special_bonds charmm)
#   * angle_style cosine/squared    (MARTINI 3 IDP backbone funct=10)
#   * no fix cmap                   (CMAP is CHARMM-only)
#   * comm_modify cutoff 60         (MARTINI bonds longer than atomistic)
# Run from this relaxation/ directory.

{_COMMON_HEADER}
pair_style      lj/cut/coul/cut 12.0    # MARTINI: was lj/charmm/coul/long + pppm
pair_modify     shift yes
special_bonds   lj 0.0 0.0 0.0 coul 0.0 0.0 0.0   # MARTINI: was special_bonds charmm
dielectric      15.0                              # MARTINI: RF approx (no equivalent in CHARMM)

read_data       system_ramped.data
include         ../{base_name}.in.groups
include         ../{base_name}.in.settings

neigh_modify    one 10000
comm_modify     mode single cutoff 60.0           # MARTINI: longer than CHARMM atomistic

thermo          100
thermo_style    custom step pe ke etotal evdwl ecoul epair ebond eangle edihed eimp press vol temp

# --- Tight minimisation (mirrors topro stage 3) ---
min_style       cg
minimize        1.0e-6 1.0e-8 100000 1000000
write_data      system_minimized_final.data

# --- Short NVT (5000 steps x 1 fs = 5 ps), T=310K is the MARTINI canonical ---
reset_timestep  0
variable        T equal 310.0                     # MARTINI: 310 K (topro CHARMM used 300 K)
velocity        all create ${{T}} 12345
timestep        1.0                               # same as topro CHARMM stage 3
fix             1 all nvt temp ${{T}} ${{T}} 100.0   # same Tdamp as topro
run             5000
unfix           1
write_data      after_nvt.data

# --- Short NPT at 1 atm (5000 steps x 1 fs = 5 ps) ---
# OFF by default: for dry / vacuum boxes (no W water packed), NPT collapses
# the cell because there is no solvent pressure to balance against.
# UNCOMMENT for hydrated systems (--water-density > 0) to let the box find
# its natural MARTINI density.
#
# fix             1 all npt temp ${{T}} ${{T}} 100.0 iso 1.0 1.0 1000.0
# run             5000
# unfix           1

write_data      ../system_equilibrated.data
print           "Stage 3 done -> ../system_equilibrated.data (NVT-only; uncomment NPT block for hydrated runs)."
"""
