"""
Regression tests: SimBox POSS-containing systems.

Tests two compositions with POSS (AM0270) alongside Epoxy-PDMS and Amino-PDMS.

References:
  50% POSS: tests/output/simbox_crosslink/v4/poss_50/
  100% POSS: tests/output/simbox_crosslink/v4/poss_100/

Both generated by generate_simbox_crosslink.py with seed=42 and scaled-down
molecule counts (n_epoxy=60) to keep regression runtime manageable.

Compositions
------------
poss_50:  n_epoxy=60, n_amino=15, n_poss=15  → 9120 atoms
          POSS fraction = n_poss / (n_amino + n_poss) = 50%
poss_100: n_epoxy=60, n_amino=0,  n_poss=30  → 10470 atoms
          POSS fraction = 100% (all amino replaced by POSS)

Run with:
    pytest tests/regression/test_simbox_poss.py -v
"""

import sys
import pytest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

WORKFLOW = ROOT / "tests/workflows/generate_simbox_crosslink.py"
REF_DIR  = ROOT / "tests/output/simbox_crosslink/v4"

# Compositions
POSS_50_DIR  = REF_DIR / "poss_50"
POSS_100_DIR = REF_DIR / "poss_100"

from tests.regression.lammps_compare import assert_lammps_identical, parse_lammps_data


# ---------------------------------------------------------------------------
# Shared workflow runner
# ---------------------------------------------------------------------------

def _run_workflow(tmp_path_factory, n_epoxy, n_amino, n_poss, label):
    if not WORKFLOW.exists():
        pytest.skip(f"Workflow not found: {WORKFLOW}")
    output_dir = tmp_path_factory.mktemp(label)
    import subprocess
    result = subprocess.run(
        [sys.executable, str(WORKFLOW),
         "--output", str(output_dir),
         "--n_epoxy", str(n_epoxy),
         "--n_amino", str(n_amino),
         "--n_poss",  str(n_poss),
         "--seed", "42"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        pytest.fail(f"Workflow failed:\n{result.stderr}")
    return output_dir


# ---------------------------------------------------------------------------
# poss_50  (50% POSS)
# ---------------------------------------------------------------------------

class TestPoss50Structure:
    """Structural tests against the frozen poss_50 reference (no new run)."""

    @pytest.fixture(scope="class")
    def ref(self):
        path = POSS_50_DIR / "system.data"
        if not path.exists():
            pytest.skip(f"Reference not found: {path}")
        return parse_lammps_data(path)

    def test_atom_count(self, ref):
        # 60×71 + 15×117 + 15×207 = 9120
        expected = 60 * 71 + 15 * 117 + 15 * 207
        assert ref.header.get("atoms") == expected, \
            f"Atom count: expected {expected}, got {ref.header.get('atoms')}"

    def test_five_atom_types(self, ref):
        assert ref.header.get("atom types") == 5, \
            f"Expected 5 atom types, got {ref.header.get('atom types')}"

    def test_has_nitrogen(self, ref):
        names = {v[1] for v in ref.masses.values()}
        assert "N_3" in names, f"N_3 missing from masses, found: {names}"

    def test_has_silicon(self, ref):
        names = {v[1] for v in ref.masses.values()}
        assert "Si3" in names, f"Si3 missing from masses, found: {names}"

    def test_n3_at_type4(self, ref):
        assert ref.masses.get(4, (None, ""))[1] == "N_3", \
            f"Expected N_3 at type 4, got: {ref.masses.get(4)}"

    def test_pair_coeffs_count(self, ref):
        assert len(ref.pair_coeffs) == ref.header.get("atom types")

    def test_reactive_groups_file_exists(self):
        assert (POSS_50_DIR / "groups.txt").exists(), \
            "groups.txt missing from poss_50 reference"

    def test_crosslink_script_exists(self):
        assert (POSS_50_DIR / "4b_crosslink.in").exists(), \
            "4b_crosslink.in missing from poss_50 reference"

    def test_ff_coeffs_exists(self):
        assert (POSS_50_DIR / "ff_coeffs.in").exists(), \
            "ff_coeffs.in missing from poss_50 reference"


class TestPoss50Regression:
    """Regression tests: fresh run vs frozen poss_50 reference."""

    @pytest.fixture(scope="class")
    def new_output_dir(self, tmp_path_factory):
        return _run_workflow(tmp_path_factory, 60, 15, 15, "poss50_out")

    def test_system_data_identical(self, new_output_dir):
        assert_lammps_identical(
            new_output_dir / "system.data",
            POSS_50_DIR / "system.data",
            label="SimBox poss_50 system.data",
        )

    def test_groups_file_identical(self, new_output_dir):
        ref = POSS_50_DIR / "groups.txt"
        if not ref.exists():
            pytest.skip("Reference groups.txt not found")
        assert (new_output_dir / "groups.txt").read_text() == ref.read_text()

    def test_minimize_script_identical(self, new_output_dir):
        ref = POSS_50_DIR / "1_minimize.in"
        if not ref.exists():
            pytest.skip("Reference minimize script not found")
        assert (new_output_dir / "1_minimize.in").read_text() == ref.read_text()

    def test_ff_coeffs_identical(self, new_output_dir):
        ref = POSS_50_DIR / "ff_coeffs.in"
        if not ref.exists():
            pytest.skip("Reference ff_coeffs.in not found")
        assert (new_output_dir / "ff_coeffs.in").read_text() == ref.read_text()


# ---------------------------------------------------------------------------
# poss_100  (100% POSS — no Amino-PDMS)
# ---------------------------------------------------------------------------

class TestPoss100Structure:
    """Structural tests against the frozen poss_100 reference (no new run)."""

    @pytest.fixture(scope="class")
    def ref(self):
        path = POSS_100_DIR / "system.data"
        if not path.exists():
            pytest.skip(f"Reference not found: {path}")
        return parse_lammps_data(path)

    def test_atom_count(self, ref):
        # 60×71 + 0×117 + 30×207 = 10470
        expected = 60 * 71 + 0 * 117 + 30 * 207
        assert ref.header.get("atoms") == expected, \
            f"Atom count: expected {expected}, got {ref.header.get('atoms')}"

    def test_five_atom_types(self, ref):
        # POSS cage has Si, O, C, H; aminopropyl arm adds N
        assert ref.header.get("atom types") == 5, \
            f"Expected 5 atom types, got {ref.header.get('atom types')}"

    def test_has_nitrogen(self, ref):
        # POSS aminopropyl arm: -CH2CH2CH2-NH2 → N_3
        names = {v[1] for v in ref.masses.values()}
        assert "N_3" in names, f"N_3 missing from masses (aminopropyl arm), found: {names}"

    def test_n3_at_type4(self, ref):
        assert ref.masses.get(4, (None, ""))[1] == "N_3", \
            f"Expected N_3 at type 4, got: {ref.masses.get(4)}"

    def test_no_amino_pdms_species(self, ref):
        # 100% POSS means n_amino=0; all amine-functional molecules are POSS
        # System should have more atoms per amine (207 vs 117) → verify total
        expected = 60 * 71 + 30 * 207
        assert ref.header.get("atoms") == expected

    def test_reactive_groups_file_exists(self):
        assert (POSS_100_DIR / "groups.txt").exists(), \
            "groups.txt missing from poss_100 reference"

    def test_crosslink_script_exists(self):
        assert (POSS_100_DIR / "4b_crosslink.in").exists(), \
            "4b_crosslink.in missing from poss_100 reference"

    def test_ff_coeffs_exists(self):
        assert (POSS_100_DIR / "ff_coeffs.in").exists(), \
            "ff_coeffs.in missing from poss_100 reference"


class TestPoss100Regression:
    """Regression tests: fresh run vs frozen poss_100 reference."""

    @pytest.fixture(scope="class")
    def new_output_dir(self, tmp_path_factory):
        return _run_workflow(tmp_path_factory, 60, 0, 30, "poss100_out")

    def test_system_data_identical(self, new_output_dir):
        assert_lammps_identical(
            new_output_dir / "system.data",
            POSS_100_DIR / "system.data",
            label="SimBox poss_100 system.data",
        )

    def test_groups_file_identical(self, new_output_dir):
        ref = POSS_100_DIR / "groups.txt"
        if not ref.exists():
            pytest.skip("Reference groups.txt not found")
        assert (new_output_dir / "groups.txt").read_text() == ref.read_text()

    def test_minimize_script_identical(self, new_output_dir):
        ref = POSS_100_DIR / "1_minimize.in"
        if not ref.exists():
            pytest.skip("Reference minimize script not found")
        assert (new_output_dir / "1_minimize.in").read_text() == ref.read_text()

    def test_ff_coeffs_identical(self, new_output_dir):
        ref = POSS_100_DIR / "ff_coeffs.in"
        if not ref.exists():
            pytest.skip("Reference ff_coeffs.in not found")
        assert (new_output_dir / "ff_coeffs.in").read_text() == ref.read_text()
