"""
Regression tests: SimBox crosslink system (POSS + Epoxy-PDMS + Amino-PDMS).

Reference: tests/output/simbox_crosslink/v3/poss_0/
Workflow:  tests/workflows/generate_simbox_crosslink.py

Run with:
    pytest tests/regression/test_simbox_crosslink.py -v
"""

import sys
import pytest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

# v4 poss_0 composition: n_epoxy=600, n_amino=300, n_poss=0, seed=42
# (600*71 + 300*117 = 77700 atoms)
# Generated by generate_simbox_crosslink.py (current canonical legacy script)
# with writer.py fix: max(dihedral_types.values()) not len(dihedral_types)
REF_DIR = ROOT / "tests/output/simbox_crosslink/v4/poss_0"
N_EPOXY, N_AMINO, N_POSS = 600, 300, 0
WORKFLOW = ROOT / "tests/workflows/generate_simbox_crosslink.py"

from tests.regression.lammps_compare import assert_lammps_identical, parse_lammps_data


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def ref_data():
    path = REF_DIR / "system.data"
    if not path.exists():
        pytest.skip(f"Reference file not found: {path}")
    return parse_lammps_data(path)


@pytest.fixture(scope="module")
def new_output_dir(tmp_path_factory):
    if not WORKFLOW.exists():
        pytest.skip(f"Workflow not found: {WORKFLOW}")
    output_dir = tmp_path_factory.mktemp("simbox_output")
    import subprocess
    result = subprocess.run(
        [sys.executable, str(WORKFLOW),
         "--output", str(output_dir),
         "--n_epoxy", str(N_EPOXY), "--n_amino", str(N_AMINO),
         "--n_poss", str(N_POSS), "--seed", "42"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        pytest.fail(f"Workflow failed:\n{result.stderr}")
    return output_dir


# ---------------------------------------------------------------------------
# Structure Tests (reference introspection — no new run needed)
# ---------------------------------------------------------------------------

class TestSimboxStructure:
    def test_universal_atom_types(self, ref_data):
        # Universal map: Si3=1, O_3=2, C_3=3, N_3=4, H_=5 (generate_simbox_crosslink.py ordering)
        assert ref_data.header.get("atom types") == 5, \
            f"Expected 5 universal atom types, got {ref_data.header.get('atom types')}"

    def test_expected_atom_count(self, ref_data):
        # v3 poss_0: 600 epoxy (71 atoms) + 300 amino (117 atoms) + 0 poss = 77700
        expected = N_EPOXY * 71 + N_AMINO * 117 + N_POSS * 207
        actual = ref_data.header.get("atoms", 0)
        assert actual == expected, f"Atom count: expected {expected}, got {actual}"

    def test_pair_coeffs_count(self, ref_data):
        n_types = ref_data.header.get("atom types", 0)
        assert len(ref_data.pair_coeffs) == n_types

    def test_has_nitrogen_type(self, ref_data):
        # N_3 should be present at type ID 4 (universal map: N_3=4, H_=5)
        names = {v[1] for v in ref_data.masses.values()}
        assert "N_3" in names, f"N_3 missing from atom types, found: {names}"
        assert ref_data.masses.get(4, (None, ""))[1] == "N_3", \
            f"Expected N_3 at type 4, got: {ref_data.masses.get(4)}"

    def test_reactive_groups_file_exists(self):
        groups_file = REF_DIR / "groups.txt"
        assert groups_file.exists(), "groups.txt missing from reference output"

    def test_crosslink_script_exists(self):
        crosslink_file = REF_DIR / "4b_crosslink.in"
        assert crosslink_file.exists(), "4b_crosslink.in missing from reference output"


# ---------------------------------------------------------------------------
# Regression Tests
# ---------------------------------------------------------------------------

class TestSimboxRegression:
    def test_system_data_identical(self, new_output_dir):
        new_path = new_output_dir / "system.data"
        ref_path = REF_DIR / "system.data"
        assert_lammps_identical(new_path, ref_path, label="SimBox system.data")

    def test_groups_file_identical(self, new_output_dir):
        new_path = new_output_dir / "groups.txt"
        ref_path = REF_DIR / "groups.txt"
        if not ref_path.exists():
            pytest.skip("Reference groups.txt not found")
        assert new_path.read_text() == ref_path.read_text()

    def test_minimize_script_identical(self, new_output_dir):
        new_path = new_output_dir / "1_minimize.in"
        ref_path = REF_DIR / "1_minimize.in"
        if not ref_path.exists():
            pytest.skip("Reference minimize script not found")
        assert new_path.read_text() == ref_path.read_text()

    def test_ff_coeffs_identical(self, new_output_dir):
        new_path = new_output_dir / "ff_coeffs.in"
        ref_path = REF_DIR / "ff_coeffs.in"
        if not ref_path.exists():
            pytest.skip("Reference ff_coeffs.in not found")
        if not new_path.exists():
            pytest.skip("Workflow does not generate ff_coeffs.in (only setup_crosslink.py did)")
        assert new_path.read_text() == ref_path.read_text()
