"""
LAMMPS input script generator for simbox.

Generates a multi-stage simulation protocol:

1. **Soft push-off minimization** – resolve initial overlaps.
2. **Energy minimization** – conjugate-gradient with real potentials.
3. **NVT equilibration** – thermalise at the target temperature.
4. **NPT equilibration** – relax to the correct density.
5. **Crosslink template** – commented-out blocks for ``fix bond/react``
   and ``fix bond/create`` that the user can configure.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from topon.simbox.system import AssembledSystem


def write_inputs(
    system: AssembledSystem,
    output_dir: str,
    temperature: float = 300.0,
    pressure: float = 1.0,
    data_filename: str = "system.data",
    groups_filename: str = "groups.txt",
    include_crosslink: bool = True,
) -> dict[str, str]:
    """Generate all LAMMPS input scripts.

    Parameters
    ----------
    system : AssembledSystem
        Merged system (used for metadata only).
    output_dir : str
        Target directory.
    temperature : float
        Target temperature in K.
    pressure : float
        Target pressure in atm.
    data_filename : str
        Name of the data file (must match what ``writer.write_lammps`` produced).
    groups_filename : str
        Name of the groups file.

    Returns
    -------
    dict[str, str]
        Mapping from logical name to file path.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    paths: dict[str, str] = {}

    # Stage 1 – soft push-off + CG minimization
    p = out / "1_minimize.in"
    _write_minimize_script(p, system, data_filename, groups_filename, temperature)
    paths["minimize"] = str(p)

    # Stage 2 – NVT equilibration
    p = out / "2_nvt.in"
    _write_nvt_script(p, system, temperature)
    paths["nvt"] = str(p)

    # Stage 3 – NPT equilibration
    p = out / "3_npt.in"
    _write_npt_script(p, system, temperature, pressure)
    paths["npt"] = str(p)

    # Stage 4 – crosslink setup (only for reactive systems)
    if include_crosslink:
        p = out / "4b_crosslink.in"
        _write_crosslink_template(p, system, temperature)
        paths["crosslink"] = str(p)

    print(f"[Inputs] Wrote {len(paths)} input scripts to {out}")
    return paths


# ======================================================================
# Stage 1 – Minimization (soft push-off → real potential)
# ======================================================================

def _write_minimize_script(
    path: Path,
    system: AssembledSystem,
    data_file: str,
    groups_file: str,
    temperature: float,
) -> None:
    lx, ly, lz = system.box_lengths
    script = f"""\
# =============================================================
# Stage 1: Soft push-off + energy minimization
# Generated by topon.simbox
# =============================================================

units           real
atom_style      full
boundary        p p p

# -- Force field styles (must be declared before read_data) --
bond_style      harmonic
angle_style     harmonic
dihedral_style  harmonic
improper_style  cvff
special_bonds   dreiding

pair_style      lj/cut 12.0
pair_modify     mix arithmetic

read_data       {data_file}
include         {groups_file}

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

thermo          100
thermo_style    custom step temp pe ke etotal press vol density

# ==============================================================
# Phase A: Soft push-off (resolve initial overlaps)
# ==============================================================
pair_style      soft 5.0
pair_coeff      * * 0.0

variable        prefactor equal ramp(0,60)
fix             soft_push all adapt 1 pair soft a * * v_prefactor

fix             soft_nvt all nvt temp {temperature} {temperature} 100.0
timestep        0.5
run             10000
unfix           soft_nvt
unfix           soft_push

# ==============================================================
# Phase B: Switch to DREIDING LJ + energy minimization
# ==============================================================
pair_style      lj/cut 12.0
include         settings.in

min_style       cg
minimize        1.0e-4 1.0e-6 10000 100000

# Brief NVT to thermalise after minimization
fix             min_nvt all nvt temp {temperature} {temperature} 100.0
timestep        1.0
run             10000
unfix           min_nvt

write_data      system_minimized.data
write_restart   restart.minimize

print "Stage 1 complete"
"""
    with open(path, "w") as f:
        f.write(script)


# ======================================================================
# Stage 2 – NVT equilibration
# ======================================================================

def _write_nvt_script(
    path: Path, system: AssembledSystem, temperature: float
) -> None:
    script = f"""\
# =============================================================
# Stage 2: NVT equilibration
# Generated by topon.simbox
# =============================================================

units           real
atom_style      full
boundary        p p p

bond_style      harmonic
angle_style     harmonic
dihedral_style  harmonic
improper_style  cvff
special_bonds   dreiding

pair_style      lj/cut 12.0
pair_modify     mix arithmetic

read_restart    restart.minimize
include         settings.in

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

thermo          500
thermo_style    custom step temp pe ke etotal press vol density lx ly lz

fix             nvt_eq all nvt temp {temperature} {temperature} 100.0
timestep        1.0

run             50000

unfix           nvt_eq

write_data      system_nvt.data
write_restart   restart.nvt

print "Stage 2 (NVT) complete"
"""
    with open(path, "w") as f:
        f.write(script)


# ======================================================================
# Stage 3 – NPT equilibration
# ======================================================================

def _write_npt_script(
    path: Path,
    system: AssembledSystem,
    temperature: float,
    pressure: float,
) -> None:
    script = f"""\
# =============================================================
# Stage 3: NPT equilibration
# Generated by topon.simbox
# =============================================================

units           real
atom_style      full
boundary        p p p

bond_style      harmonic
angle_style     harmonic
dihedral_style  harmonic
improper_style  cvff
special_bonds   dreiding

pair_style      lj/cut 12.0
pair_modify     mix arithmetic

read_restart    restart.nvt
include         settings.in

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

thermo          500
thermo_style    custom step temp pe ke etotal press vol density lx ly lz

fix             npt_eq all npt temp {temperature} {temperature} 100.0 &
                iso {pressure} {pressure} 1000.0
timestep        1.0

run             100000

unfix           npt_eq

write_data      system_npt.data
write_restart   restart.npt

print "Stage 3 (NPT) complete – system should now be at target density"
"""
    with open(path, "w") as f:
        f.write(script)


# ======================================================================
# Stage 4 – Crosslink template
# ======================================================================

def _write_crosslink_template(
    path: Path, system: AssembledSystem, temperature: float
) -> None:
    # Collect unique reactive group names for documentation
    reactive_groups = sorted(set(e.group_name for e in system.reactive_sites))
    groups_doc = ", ".join(reactive_groups) if reactive_groups else "(none detected)"

    script = f"""\
# =============================================================
# Stage 4b: Crosslink reaction
# Generated by topon.simbox
#
# Detected reactive groups: {groups_doc}
#
# This file provides commands for two crosslinking
# approaches.  Uncomment and configure the one you need.
# =============================================================

units           real
atom_style      full
boundary        p p p

read_restart    restart.npt

pair_style      lj/cut 12.0
pair_modify     mix arithmetic

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

# Include reactive-group definitions
include         groups.txt

thermo          500
thermo_style    custom step temp pe ke etotal press vol density

fix             rxn_nvt all nvt temp {temperature} {temperature} 100.0
timestep        1.0

# ==============================================================
# OPTION A: fix bond/react  (template-based, most flexible)
# ==============================================================
# You need pre-reaction and post-reaction molecule templates.
# See: https://docs.lammps.org/fix_bond_react.html
#
# fix  rxn all bond/react stabilization yes nvt_grp &
#      react epoxy_amine all 100 3.5 &
#          pre_react_template.data post_react_template.data &
#          map_file.txt
#
# -- Replace the file names with your actual templates --

# ==============================================================
# OPTION B: fix bond/create  (simpler, distance-based)
# ==============================================================
# Creates bonds between atom types within a cutoff distance.
# See: https://docs.lammps.org/fix_bond_create.html
#
# fix  bc all bond/create 100 <type_epoxide_C> <type_amine_N> &
#      3.5 <new_bond_type> prob 0.5 {int(temperature)}
#
# -- Replace <type_...> with the LAMMPS numeric atom types
#    from your data file --

# ==============================================================
# Production run (with reaction fix active)
# ==============================================================
# run  500000

# unfix rxn_nvt
# write_data system_crosslinked.data
# write_restart restart.crosslinked

print "Stage 4 template loaded – configure crosslink fix above"
"""
    with open(path, "w") as f:
        f.write(script)
